### PR TITLE
Grand stability upgrade #3

### LINKED ISSUE #218: Snackbar re-shows when returning from settings screen
When you return from settings screen the snackbar e.g. "19 pokemon found..." shows up again, even tho the map has been cleared.

### LINKED ISSUE #219: NullPointerException and crash
Due to MapWrapperFragment:

  private void initMap() {

```
    pokeSnackbar = Snackbar.make(getView(), "", Snackbar.LENGTH_LONG);
```

-> getView() can be null -- e.g. when you are in the theme screen and the location changes.
initMap gets called in a listener callback for when the location changes.

### LINKED ISSUE #270: apk freezes if it was running in the background for a while
If Pokemap was running in the background for a while and i try to scan manually, nothing happens. The only way to fix this, is to restart the app. Are there more people who have this problem?

### PR DESCRIPTION
**Pull request by kyr0**
- The NotificationService now doesn't start multiple instances anymore -- there only once service instance at a time. probably fixed #270, probably #208
- Now the NotificationService doesn't call getCatchablePokemon() every 60ms (Uff..., and this bug  was for multiple instances before and interacted with the EventBus...!); probably fixed #270, #246 
- Fixed two crashes (ArrayOutOfBounds, NullPointer), fixes #219, probably #166
- Fixed Snackbar shows up after returning from SettingsActivity (also doesn't search & zoom in) -- it just shows the map at the location you are at the moment., fixes #218
- Map suggestion remembers that you closed it. Never shows up again.

### CODE REVIEW

**Comment by comann** [comment]
Is this gtg?

File: app/src/main/java/com/omkarmoghe/pokemap/views/MainActivity.java [hunk 1]
```diff
@@ -170,6 +170,12 @@ public void onRequestPermissionsResult(int requestCode, @NonNull String[] permis
     }
 
     private void startNotificationService(){
+
+        // check for if the service is already running
+        if (PokemonNotificationService.isRunning()) {
+            stopNotificationService();
```
Comment (s7092910) [inline app/src/main/java/com/omkarmoghe/pokemap/views/MainActivity.java:176]: If we are starting the service, why are we turning it off then back on again? Wouldn't it just be better if we are starting the notification service, if it is running just to let it keep running the same instance? So if it wasn't running then you turn it on.

File: app/src/main/java/com/omkarmoghe/pokemap/views/map/MapWrapperFragment.java [hunk 2]
```diff
@@ -206,42 +205,71 @@ public void onClick(View view) {
...
+                            .setMessage(getString(R.string.enable_location_permission_message))
+                            .setPositiveButton(getString(R.string.button_ok), null)
+                            .show();
+                    return;
+                }
+                mGoogleMap.setMyLocationEnabled(true);
+
+                LatLng currentLatLngLocation = new LatLng(mLocation.getLatitude(), mLocation.getLongitude());
+
+                if (animateZoomIn) {
```
Comment (s7092910) [inline app/src/main/java/com/omkarmoghe/pokemap/views/map/MapWrapperFragment.java:248]: I still think we shouldn't have the zoom at all.

**Comment by s7092910** [comment]
Besides those 2 line comments. It looks good to me.

File: app/src/main/java/com/omkarmoghe/pokemap/views/MainActivity.java (hunk 1 above)
Comment (kyr0) [inline app/src/main/java/com/omkarmoghe/pokemap/views/MainActivity.java:176]: True, this is a quick fix, not a refactoring; sadly the reality is that the service is started/stopped onResume/onPause in MainActivity. I just think it's better to put a quick fix now, than let the app spawn as many processes as the user interacts with the app (as it was before); with this architecture, I also don't see an easy option, because the service should start when the App is not actively used. That is why the code starts the service in onPause() and stops in onResume(). For sure, it also starts/stops then when the user comes back from SettingsActivity or enters from LoginActivity. But we can't just say "let the instance live" because then the service would actively report / notify while the user uses the app. (This means: Notifying that there are new Pokemon and calling getCatchablePokemon() while the user looks at the map).

File: app/src/main/java/com/omkarmoghe/pokemap/views/map/MapWrapperFragment.java (hunk 2 above)
Comment (kyr0) [inline app/src/main/java/com/omkarmoghe/pokemap/views/map/MapWrapperFragment.java:248]: Fine, can be a team decision also. @comann If you like to take a decision on that: just change the call "animateCamera" to "moveCamera" instead to deactivate zooming animation.

File: app/src/main/java/com/omkarmoghe/pokemap/views/MainActivity.java (hunk 1 above)
Comment (s7092910) [inline app/src/main/java/com/omkarmoghe/pokemap/views/MainActivity.java:176]: They both are quick fixes. Just having it check to see if the service is running, if it is it does nothing is better than stopping it and starting it again. In fact you get better performance if you keep it running instead of stopping and starting it.

EDIT: Kyr0 I don't think you understand what I'm talking about. This method is called to start the service. It shouldn't be stopping the service and starting the service if the service is running. So the method would be

`private void startNotificationService(){
        // check for if the service is already running
        if (!PokemonNotificationService.isRunning()) {
            Intent intent = new Intent(this, PokemonNotificationService.class);
            startService(intent);
        }
    }`

So when 'startNotificationService' is called, it is only going to start the service if it is not currently running. The way you have it now,  when 'startNotificationService' is called if the service is not running it will start the service. But if the service is running, you are stopping the service and then restarting the service in this method. I hope that is clear enough.

**Comment by rohanjain1** [comment]
@s7092910 : please put discussed fixes on top of this
